spring:
  application:
    name: to-do-list
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/to_do_list?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    #clean-disabled: false
    #clean-on-validation-error: true
    #check-location: true

logging:
  level:
    root: WARN
    #org.flywaydb.core: DEBUG
    #org.springframework.boot.autoconfigure.flyway: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG